name: Run simple tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .         # Installs your package in editable mode
        pip install pytest       # Add any other testing tools if needed

    - name: Run tests
      run: PYTHONPATH=. pytest -W ignore::DeprecationWarning -v tests
